apiVersion: v1
kind: Pod
metadata:
  name: debug-pod
spec:
  containers:
  - image: ghcr.io/soli0222/debug-image:latest
    name: debug
    resources:
      requests:
        memory: "128Mi"
        cpu: "100m"
      limits:
        memory: "512Mi"
        cpu: "500m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
